name: rl
channels:
  - conda-forge
  - crowdai
  - pytorch
  - nvidia
dependencies:
  - python=3.7
  - pip
  - malmo
  - gym=0.19
  - numpy
  - tqdm
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - pip:
    - marlo
    - psutil
    - tensorboard
